title = "Custom Boost Gitleaks configuration"

[extend]
useDefault = true

[[rules]]
id = "generic-api-key"

    [[rules.allowlists]]
    description = "Don't report on URI"
    regexTarget = "match"
    regexes = [
        '''(?i)(?:[\w]+\.)+[\w]+:[0-9]{1,5}(?:/[\w]+)+''',
    ]
    
    [[rules.allowlists]]
    regexTarget = "line"  
    regexes = [ '''(?i)publicKeyToken="[^"]+"''' ]
    paths = [ '''(?i)web\.config''' ]
    
    [[rules.allowlists]]
    description = "Don't report on translation"
    regexTarget = "line"
    regexes = [ '''(?i)xmi:type="utility:TranslatableString"''' ]
    paths = [ '''(?i)\.msgflow$''' ]