name: Scan Rules DB and Namespaces
on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize

permissions:
  contents: read
  
jobs:
  scan_job:
    name: Scanner Registry Action
    runs-on: "ubuntu-latest"

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@128a63446a954579617e875aaab7d2978154e969 # v2.4.0
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0
      - name: Scan Registry
        uses: boostsecurityio/scanner-registry-action@46e7400ddf34338f35563f6b9d357c03d315d674 # v1.4.0
        with:
          api_endpoint: ${{ vars.BOOST_API_ENDPOINT }}
          api_token: ${{ secrets.BOOST_SYSTEM_API_KEY_REGISTRY }}
